### ISSUE TITLE
"Neither python -m pip nor uv are available" error comes on starting ComfyUI with ComfyUI-Manager

### ISSUE THREAD

**Issue by chandujr** [ltdrdata/ComfyUI-Manager#2201]
**OS:** Nobara Linux 42 KDE
**ComfyUI:** v0.3.64
**ComfyUI-Manager:** v3.37

---

I was using ComfyUI and ComfyUI-Manager using Python v3.13 venv until yesterday. Today I deleted that venv folder and created a new one with Python v3.12. Then I reinstalled ComfyUI pip requirements and tried to start the server using the command `python main.py` in the activated venv. But I got this error:

```
venv ❯ python main.py
[START] Security scan
[ComfyUI-Manager] Neither python -m pip nor uv are available. Cannot proceed with package operations.
Failed to execute startup-script: /home/username/Applications/ComfyUI/custom_nodes/comfyui-manager/prestartup_script.py / Neither pip nor uv are available for package management
```

`pip` is installed and listed as a module when I check `pip list`.

See the output of this command:
```
venv ❯ python -c "import subprocess; print(subprocess.run(['python', '-m', 'pip', '--version'], capture_output=True, text=True))"
CompletedProcess(args=['python', '-m', 'pip', '--version'], returncode=0, stdout='pip 25.2 from /home/username/Applications/ComfyUI/venv/lib64/python3.12/site-packages/pip (python 3.12)\n', stderr='')
```

Doesn't this mean that `pip` is properly installed? Then why is that error showing up?

**Comment by devjoda** [comment]
+1 for this, I have same issue

**Comment by chandujr** [comment]
Not sure whether this is ideal, but what I did to solve this was to set `use_uv = False` in the ComfyUI-Manager file: `/home/username/Applications/ComfyUI/user/default/ComfyUI-Manager/config.ini`. It was set to `True` there by default.

**Comment by DarthDiabolik** [comment]
I installed 25H2 and I thought this error was due to the new system or a bug in 25H2, I installed other versions of Python several times and the thing keeps happening, comfyui won't start and the same error always appears

[ComfyUI-Manager] python -m pip not available. Falling back to uv.
[ComfyUI-Manager] Neither python -m pip nor uv are available. Cannot proceed with package operations.
Failed to execute startup-script: E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\prestartup_script.py / Neither pip nor uv are available for package management

Then I went back to 24H2, first start and everything is fine (too long to open but I was happy that the program started), I install the manager and the start is normal, I even manage to make some pictures! This morning I start the program again and the same error repeats, I really have no idea what else to do, I tried everything I could think of and what I found on the internet

**Comment by chandujr** [comment]
@DarthDiabolik Did you try [this](https://github.com/Comfy-Org/ComfyUI-Manager/issues/2201#issuecomment-3394128516)?

> Not sure whether this is ideal, but what I did to solve this was to set use_uv = False in the ComfyUI-Manager file: /home/username/Applications/ComfyUI/user/default/ComfyUI-Manager/config.ini. It was set to True there by default.

**Comment by DarthDiabolik** [comment]
First of all, thank you for your help and answer, secondly (I know it sounds stupid) I'm glad I'm not alone with this problem, because after a few days of searching this is the first time I've found someone with a similar problem (at one point I even thought that maybe my GPU was causing this problem)! Unfortunately, your solution didn't help me, in my ini. file use_uv = was already set to False, I changed it to True and that didn't help either, the problem still exists! In any case, thank you, if I find a solution I'll let you know

**Comment by devjoda** [comment]
> First of all, thank you for your help and answer, secondly (I know it sounds stupid) I'm glad I'm not alone with this problem, because after a few days of searching this is the first time I've found someone with a similar problem (at one point I even thought that maybe my GPU was causing this problem)! Unfortunately, your solution didn't help me, in my ini. file use_uv = was already set to False, I changed it to True and that didn't help either, the problem still exists! In any case, thank you, if I find a solution I'll let you know

I also attempted the suggested fix running on a portable windows version of comfy. No luck. Proably not much help, but I ended up setting up a linux mint partition and it solved the issue. Can really recommend switching. No more headaches with dependencies.

**Comment by DarthDiabolik** [comment]
> I also attempted the suggested fix running on a portable windows version of comfy. No luck. Proably not much help, but I ended up setting up a linux mint partition and it solved the issue. Can really recommend switching. No more headaches with dependencies.

I used Zorin OS which is also fantastic but I had  some problems with Photoshop and with some other programs and I returned to Windows again two years ago , since nothing of programs binds me to windows anymore there is a big possibility that I will soon switch again to either Zorin or Mint ! Otherwise the problem is definitely in the manager and probably also in the ini file, since I changed this suggested option, I returned to the False option again and Comfyui started and still shows that it is not reading pip and that it has switched to uv ,Honestly, for the last 6-7 months I've been afraid to update ComfyUI or Manager because I have some problems every time.

**Comment by lazycodeman** [comment]
Have you installed the requirements of ComfyUI-Manager? I have just fixed the error by:
`pip install -r path-to-your-comfyui-installed-location/custom_nodes/ComfyUI-Manager/requirements.txt`
Hope this help.

**Comment by LazerVV** [comment]
Linux:

```
python -m pip install uv
```

Do this OUTSIDE of the venv. Fixes issue.

**Comment by MalikKillian** [comment]
This was happening for me as well but I was able to fix the error on startup by setting `use_uv = False` in `/home/comfyuser/ComfyUI/user/__manager/config.ini`.

_However, this doesn't completely eliminate the error_. I will still get this error if I try to install a new extension from the UI.
