### ISSUE TITLE
"Cannot connect to comfyregistry" - this is still throwing errors (despite being referred to as a closed issue.)

### ISSUE THREAD

**Issue by lioncrud** [ltdrdata/ComfyUI-Manager#2423]
Did a brand new, clean install today of ComfyUI desktop and Manager.  Got thrown the logs below. Also not able to install custom nodes (getting the "failed to get custom node list" error too)

[ComfyUI-Manager] The ComfyRegistry cache update is still in progress, so an outdated cache is being used.
[ComfyUI-Manager] An invalid channel was used: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
Error handling request from 127.0.0.1
Traceback (most recent call last):
  File "C:\Ai\Comfy_F\AI_Python\3.10\lib\site-packages\aiohttp\web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
  File "C:\Ai\Comfy_F\AI_Python\3.10\lib\site-packages\aiohttp\web_app.py", line 569, in _handle
    return await handler(request)
  File "C:\Ai\Comfy_F\AI_Python\3.10\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Ai\Comfy_Manual\ComfyUI\middleware\cache_middleware.py", line 27, in cache_control
    response: web.Response = await handler(request)
  File "C:\Ai\Comfy_Manual\ComfyUI\server.py", line 81, in deprecation_warning
    response: web.Response = await handler(request)
  File "C:\Ai\Comfy_Manual\ComfyUI\server.py", line 171, in origin_only_middleware
    response = await handler(request)
  File "C:\Ai\Comfy_Manual\ComfyUI\custom_nodes\comfyui-manager\glob\manager_server.py", line 882, in fetch_customnode_list
    node_packs = await core.get_unified_total_nodes(channel, request.rel_url.query["mode"], 'cache')
  File "C:\Ai\Comfy_Manual\ComfyUI\custom_nodes\comfyui-manager\glob\manager_core.py", line 2957, in get_unified_total_nodes
    res = await unified_manager.get_custom_nodes(channel, mode)
  File "C:\Ai\Comfy_Manual\ComfyUI\custom_nodes\comfyui-manager\glob\manager_core.py", line 885, in get_custom_nodes
    nodes = await self.load_nightly(channel, mode)
  File "C:\Ai\Comfy_Manual\ComfyUI\custom_nodes\comfyui-manager\glob\manager_core.py", line 855, in load_nightly
    raise InvalidChannel(channel_url)
manager_core.InvalidChannel: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main

**Comment by ClayShoaf** [comment]
Same issue. I tried installing everything from scratch just to see the state of things. Guess I won't update my old install.

**Comment by ClayShoaf** [comment]
Same thing. Fresh install, but I'm on linux.

**EDIT:** I didn't realize `--enable-manager` and `--enable-manager-legacy-ui` had to both be used to get the legacy manager. I cloned the manager repo into `custom_nodes` to solve this, and it seems this was the source of my problem. After a quick `rm -rf` on the manager repo directory and then running `python main.py --eneable-manager --enable-manager-legacy-ui` the problem was solved.

**Comment by tobiaswuerth** [comment]
same here, still happening. completly fresh install of portable windows version

**Comment by tobiaswuerth** [comment]
ah.. I managed to solve it by selecting a 'channel' in the popup. after the clean install, nothing was selected by default.

<img width="919" height="521" alt="Image" src="https://github.com/user-attachments/assets/8b00dc76-74b2-445e-b533-eb356f85f318" />

**Comment by dt880pro** [comment]
**ubuntu 22.04 here**
pip uninstall the manager.

**Follow 1st methd:**
Go to ComfyUI/custom_nodes dir in terminal (cmd)
git clone https://github.com/ltdrdata/ComfyUI-Manager comfyui-manager
download ~100+MB
Restart ComfyUI

**You shoul see manager can fetch data:**
File "/home/dt990pro/miniconda3/envs/comfy/lib/python3.13/site-packages/aiohttp/connector.py", line 1333, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [Multiple exceptions: [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 111] Connect call failed ('::', 443, 0, 0)]
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 5/136
FETCH ComfyRegistry Data: 10/136
FETCH ComfyRegistry Data: 15/136
FETCH ComfyRegistry Data: 20/136
FETCH ComfyRegistry Data: 25/136
FETCH ComfyRegistry Data: 30/136
FETCH ComfyRegistry Data: 35/136
FETCH ComfyRegistry Data: 40/136
FETCH ComfyRegistry Data: 45/136
FETCH ComfyRegistry Data: 50/136
FETCH ComfyRegistry Data: 55/136
FETCH ComfyRegistry Data: 60/136
FETCH ComfyRegistry Data: 65/136
FETCH ComfyRegistry Data: 70/136
